/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "gtfs-realtime.pb-c.h"
void   transit_realtime__feed_message__init
                     (TransitRealtime__FeedMessage         *message)
{
  static TransitRealtime__FeedMessage init_value = TRANSIT_REALTIME__FEED_MESSAGE__INIT;
  *message = init_value;
}
size_t transit_realtime__feed_message__get_packed_size
                     (const TransitRealtime__FeedMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__feed_message__pack
                     (const TransitRealtime__FeedMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__feed_message__pack_to_buffer
                     (const TransitRealtime__FeedMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__FeedMessage *
       transit_realtime__feed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__FeedMessage *)
     protobuf_c_message_unpack (&transit_realtime__feed_message__descriptor,
                                allocator, len, data);
}
void   transit_realtime__feed_message__free_unpacked
                     (TransitRealtime__FeedMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__feed_header__init
                     (TransitRealtime__FeedHeader         *message)
{
  static TransitRealtime__FeedHeader init_value = TRANSIT_REALTIME__FEED_HEADER__INIT;
  *message = init_value;
}
size_t transit_realtime__feed_header__get_packed_size
                     (const TransitRealtime__FeedHeader *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__feed_header__pack
                     (const TransitRealtime__FeedHeader *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__feed_header__pack_to_buffer
                     (const TransitRealtime__FeedHeader *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__FeedHeader *
       transit_realtime__feed_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__FeedHeader *)
     protobuf_c_message_unpack (&transit_realtime__feed_header__descriptor,
                                allocator, len, data);
}
void   transit_realtime__feed_header__free_unpacked
                     (TransitRealtime__FeedHeader *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__feed_entity__init
                     (TransitRealtime__FeedEntity         *message)
{
  static TransitRealtime__FeedEntity init_value = TRANSIT_REALTIME__FEED_ENTITY__INIT;
  *message = init_value;
}
size_t transit_realtime__feed_entity__get_packed_size
                     (const TransitRealtime__FeedEntity *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_entity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__feed_entity__pack
                     (const TransitRealtime__FeedEntity *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_entity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__feed_entity__pack_to_buffer
                     (const TransitRealtime__FeedEntity *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_entity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__FeedEntity *
       transit_realtime__feed_entity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__FeedEntity *)
     protobuf_c_message_unpack (&transit_realtime__feed_entity__descriptor,
                                allocator, len, data);
}
void   transit_realtime__feed_entity__free_unpacked
                     (TransitRealtime__FeedEntity *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__feed_entity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__trip_update__stop_time_event__init
                     (TransitRealtime__TripUpdate__StopTimeEvent         *message)
{
  static TransitRealtime__TripUpdate__StopTimeEvent init_value = TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_EVENT__INIT;
  *message = init_value;
}
void   transit_realtime__trip_update__stop_time_update__init
                     (TransitRealtime__TripUpdate__StopTimeUpdate         *message)
{
  static TransitRealtime__TripUpdate__StopTimeUpdate init_value = TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_UPDATE__INIT;
  *message = init_value;
}
void   transit_realtime__trip_update__init
                     (TransitRealtime__TripUpdate         *message)
{
  static TransitRealtime__TripUpdate init_value = TRANSIT_REALTIME__TRIP_UPDATE__INIT;
  *message = init_value;
}
size_t transit_realtime__trip_update__get_packed_size
                     (const TransitRealtime__TripUpdate *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__trip_update__pack
                     (const TransitRealtime__TripUpdate *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__trip_update__pack_to_buffer
                     (const TransitRealtime__TripUpdate *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__TripUpdate *
       transit_realtime__trip_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__TripUpdate *)
     protobuf_c_message_unpack (&transit_realtime__trip_update__descriptor,
                                allocator, len, data);
}
void   transit_realtime__trip_update__free_unpacked
                     (TransitRealtime__TripUpdate *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__vehicle_position__init
                     (TransitRealtime__VehiclePosition         *message)
{
  static TransitRealtime__VehiclePosition init_value = TRANSIT_REALTIME__VEHICLE_POSITION__INIT;
  *message = init_value;
}
size_t transit_realtime__vehicle_position__get_packed_size
                     (const TransitRealtime__VehiclePosition *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__vehicle_position__pack
                     (const TransitRealtime__VehiclePosition *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__vehicle_position__pack_to_buffer
                     (const TransitRealtime__VehiclePosition *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__VehiclePosition *
       transit_realtime__vehicle_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__VehiclePosition *)
     protobuf_c_message_unpack (&transit_realtime__vehicle_position__descriptor,
                                allocator, len, data);
}
void   transit_realtime__vehicle_position__free_unpacked
                     (TransitRealtime__VehiclePosition *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__alert__init
                     (TransitRealtime__Alert         *message)
{
  static TransitRealtime__Alert init_value = TRANSIT_REALTIME__ALERT__INIT;
  *message = init_value;
}
size_t transit_realtime__alert__get_packed_size
                     (const TransitRealtime__Alert *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__alert__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__alert__pack
                     (const TransitRealtime__Alert *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__alert__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__alert__pack_to_buffer
                     (const TransitRealtime__Alert *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__alert__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__Alert *
       transit_realtime__alert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__Alert *)
     protobuf_c_message_unpack (&transit_realtime__alert__descriptor,
                                allocator, len, data);
}
void   transit_realtime__alert__free_unpacked
                     (TransitRealtime__Alert *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__alert__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__time_range__init
                     (TransitRealtime__TimeRange         *message)
{
  static TransitRealtime__TimeRange init_value = TRANSIT_REALTIME__TIME_RANGE__INIT;
  *message = init_value;
}
size_t transit_realtime__time_range__get_packed_size
                     (const TransitRealtime__TimeRange *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__time_range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__time_range__pack
                     (const TransitRealtime__TimeRange *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__time_range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__time_range__pack_to_buffer
                     (const TransitRealtime__TimeRange *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__time_range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__TimeRange *
       transit_realtime__time_range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__TimeRange *)
     protobuf_c_message_unpack (&transit_realtime__time_range__descriptor,
                                allocator, len, data);
}
void   transit_realtime__time_range__free_unpacked
                     (TransitRealtime__TimeRange *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__time_range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__position__init
                     (TransitRealtime__Position         *message)
{
  static TransitRealtime__Position init_value = TRANSIT_REALTIME__POSITION__INIT;
  *message = init_value;
}
size_t transit_realtime__position__get_packed_size
                     (const TransitRealtime__Position *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__position__pack
                     (const TransitRealtime__Position *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__position__pack_to_buffer
                     (const TransitRealtime__Position *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__Position *
       transit_realtime__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__Position *)
     protobuf_c_message_unpack (&transit_realtime__position__descriptor,
                                allocator, len, data);
}
void   transit_realtime__position__free_unpacked
                     (TransitRealtime__Position *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__trip_descriptor__init
                     (TransitRealtime__TripDescriptor         *message)
{
  static TransitRealtime__TripDescriptor init_value = TRANSIT_REALTIME__TRIP_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t transit_realtime__trip_descriptor__get_packed_size
                     (const TransitRealtime__TripDescriptor *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__trip_descriptor__pack
                     (const TransitRealtime__TripDescriptor *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__trip_descriptor__pack_to_buffer
                     (const TransitRealtime__TripDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__TripDescriptor *
       transit_realtime__trip_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__TripDescriptor *)
     protobuf_c_message_unpack (&transit_realtime__trip_descriptor__descriptor,
                                allocator, len, data);
}
void   transit_realtime__trip_descriptor__free_unpacked
                     (TransitRealtime__TripDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__trip_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__vehicle_descriptor__init
                     (TransitRealtime__VehicleDescriptor         *message)
{
  static TransitRealtime__VehicleDescriptor init_value = TRANSIT_REALTIME__VEHICLE_DESCRIPTOR__INIT;
  *message = init_value;
}
size_t transit_realtime__vehicle_descriptor__get_packed_size
                     (const TransitRealtime__VehicleDescriptor *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__vehicle_descriptor__pack
                     (const TransitRealtime__VehicleDescriptor *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__vehicle_descriptor__pack_to_buffer
                     (const TransitRealtime__VehicleDescriptor *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__VehicleDescriptor *
       transit_realtime__vehicle_descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__VehicleDescriptor *)
     protobuf_c_message_unpack (&transit_realtime__vehicle_descriptor__descriptor,
                                allocator, len, data);
}
void   transit_realtime__vehicle_descriptor__free_unpacked
                     (TransitRealtime__VehicleDescriptor *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__vehicle_descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__entity_selector__init
                     (TransitRealtime__EntitySelector         *message)
{
  static TransitRealtime__EntitySelector init_value = TRANSIT_REALTIME__ENTITY_SELECTOR__INIT;
  *message = init_value;
}
size_t transit_realtime__entity_selector__get_packed_size
                     (const TransitRealtime__EntitySelector *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__entity_selector__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__entity_selector__pack
                     (const TransitRealtime__EntitySelector *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__entity_selector__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__entity_selector__pack_to_buffer
                     (const TransitRealtime__EntitySelector *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__entity_selector__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__EntitySelector *
       transit_realtime__entity_selector__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__EntitySelector *)
     protobuf_c_message_unpack (&transit_realtime__entity_selector__descriptor,
                                allocator, len, data);
}
void   transit_realtime__entity_selector__free_unpacked
                     (TransitRealtime__EntitySelector *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__entity_selector__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transit_realtime__translated_string__translation__init
                     (TransitRealtime__TranslatedString__Translation         *message)
{
  static TransitRealtime__TranslatedString__Translation init_value = TRANSIT_REALTIME__TRANSLATED_STRING__TRANSLATION__INIT;
  *message = init_value;
}
void   transit_realtime__translated_string__init
                     (TransitRealtime__TranslatedString         *message)
{
  static TransitRealtime__TranslatedString init_value = TRANSIT_REALTIME__TRANSLATED_STRING__INIT;
  *message = init_value;
}
size_t transit_realtime__translated_string__get_packed_size
                     (const TransitRealtime__TranslatedString *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__translated_string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transit_realtime__translated_string__pack
                     (const TransitRealtime__TranslatedString *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__translated_string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transit_realtime__translated_string__pack_to_buffer
                     (const TransitRealtime__TranslatedString *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__translated_string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransitRealtime__TranslatedString *
       transit_realtime__translated_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransitRealtime__TranslatedString *)
     protobuf_c_message_unpack (&transit_realtime__translated_string__descriptor,
                                allocator, len, data);
}
void   transit_realtime__translated_string__free_unpacked
                     (TransitRealtime__TranslatedString *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transit_realtime__translated_string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor transit_realtime__feed_message__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedMessage, header),
    &transit_realtime__feed_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedMessage, n_entity),
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedMessage, entity),
    &transit_realtime__feed_entity__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__feed_message__field_indices_by_name[] = {
  1,   /* field[1] = entity */
  0,   /* field[0] = header */
};
static const ProtobufCIntRange transit_realtime__feed_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor transit_realtime__feed_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.FeedMessage",
  "FeedMessage",
  "TransitRealtime__FeedMessage",
  "transit_realtime",
  sizeof(TransitRealtime__FeedMessage),
  2,
  transit_realtime__feed_message__field_descriptors,
  transit_realtime__feed_message__field_indices_by_name,
  1,  transit_realtime__feed_message__number_ranges,
  (ProtobufCMessageInit) transit_realtime__feed_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue transit_realtime__feed_header__incrementality__enum_values_by_number[2] =
{
  { "FULL_DATASET", "TRANSIT_REALTIME__FEED_HEADER__INCREMENTALITY__FULL_DATASET", 0 },
  { "DIFFERENTIAL", "TRANSIT_REALTIME__FEED_HEADER__INCREMENTALITY__DIFFERENTIAL", 1 },
};
static const ProtobufCIntRange transit_realtime__feed_header__incrementality__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex transit_realtime__feed_header__incrementality__enum_values_by_name[2] =
{
  { "DIFFERENTIAL", 1 },
  { "FULL_DATASET", 0 },
};
const ProtobufCEnumDescriptor transit_realtime__feed_header__incrementality__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.FeedHeader.Incrementality",
  "Incrementality",
  "TransitRealtime__FeedHeader__Incrementality",
  "transit_realtime",
  2,
  transit_realtime__feed_header__incrementality__enum_values_by_number,
  2,
  transit_realtime__feed_header__incrementality__enum_values_by_name,
  1,
  transit_realtime__feed_header__incrementality__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const TransitRealtime__FeedHeader__Incrementality transit_realtime__feed_header__incrementality__default_value = TRANSIT_REALTIME__FEED_HEADER__INCREMENTALITY__FULL_DATASET;
static const ProtobufCFieldDescriptor transit_realtime__feed_header__field_descriptors[3] =
{
  {
    "gtfs_realtime_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedHeader, gtfs_realtime_version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incrementality",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedHeader, has_incrementality),
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedHeader, incrementality),
    &transit_realtime__feed_header__incrementality__descriptor,
    &transit_realtime__feed_header__incrementality__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedHeader, has_timestamp),
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedHeader, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__feed_header__field_indices_by_name[] = {
  0,   /* field[0] = gtfs_realtime_version */
  1,   /* field[1] = incrementality */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange transit_realtime__feed_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor transit_realtime__feed_header__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.FeedHeader",
  "FeedHeader",
  "TransitRealtime__FeedHeader",
  "transit_realtime",
  sizeof(TransitRealtime__FeedHeader),
  3,
  transit_realtime__feed_header__field_descriptors,
  transit_realtime__feed_header__field_indices_by_name,
  1,  transit_realtime__feed_header__number_ranges,
  (ProtobufCMessageInit) transit_realtime__feed_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean transit_realtime__feed_entity__is_deleted__default_value = 0;
static const ProtobufCFieldDescriptor transit_realtime__feed_entity__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_deleted",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, has_is_deleted),
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, is_deleted),
    NULL,
    &transit_realtime__feed_entity__is_deleted__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trip_update",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, trip_update),
    &transit_realtime__trip_update__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, vehicle),
    &transit_realtime__vehicle_position__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__FeedEntity, alert),
    &transit_realtime__alert__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__feed_entity__field_indices_by_name[] = {
  4,   /* field[4] = alert */
  0,   /* field[0] = id */
  1,   /* field[1] = is_deleted */
  2,   /* field[2] = trip_update */
  3,   /* field[3] = vehicle */
};
static const ProtobufCIntRange transit_realtime__feed_entity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor transit_realtime__feed_entity__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.FeedEntity",
  "FeedEntity",
  "TransitRealtime__FeedEntity",
  "transit_realtime",
  sizeof(TransitRealtime__FeedEntity),
  5,
  transit_realtime__feed_entity__field_descriptors,
  transit_realtime__feed_entity__field_indices_by_name,
  1,  transit_realtime__feed_entity__number_ranges,
  (ProtobufCMessageInit) transit_realtime__feed_entity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__trip_update__stop_time_event__field_descriptors[3] =
{
  {
    "delay",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, has_delay),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, delay),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, has_time),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncertainty",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, has_uncertainty),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeEvent, uncertainty),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__trip_update__stop_time_event__field_indices_by_name[] = {
  0,   /* field[0] = delay */
  1,   /* field[1] = time */
  2,   /* field[2] = uncertainty */
};
static const ProtobufCIntRange transit_realtime__trip_update__stop_time_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor transit_realtime__trip_update__stop_time_event__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TripUpdate.StopTimeEvent",
  "StopTimeEvent",
  "TransitRealtime__TripUpdate__StopTimeEvent",
  "transit_realtime",
  sizeof(TransitRealtime__TripUpdate__StopTimeEvent),
  3,
  transit_realtime__trip_update__stop_time_event__field_descriptors,
  transit_realtime__trip_update__stop_time_event__field_indices_by_name,
  1,  transit_realtime__trip_update__stop_time_event__number_ranges,
  (ProtobufCMessageInit) transit_realtime__trip_update__stop_time_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue transit_realtime__trip_update__stop_time_update__schedule_relationship__enum_values_by_number[3] =
{
  { "SCHEDULED", "TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_UPDATE__SCHEDULE_RELATIONSHIP__SCHEDULED", 0 },
  { "SKIPPED", "TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_UPDATE__SCHEDULE_RELATIONSHIP__SKIPPED", 1 },
  { "NO_DATA", "TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_UPDATE__SCHEDULE_RELATIONSHIP__NO_DATA", 2 },
};
static const ProtobufCIntRange transit_realtime__trip_update__stop_time_update__schedule_relationship__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex transit_realtime__trip_update__stop_time_update__schedule_relationship__enum_values_by_name[3] =
{
  { "NO_DATA", 2 },
  { "SCHEDULED", 0 },
  { "SKIPPED", 1 },
};
const ProtobufCEnumDescriptor transit_realtime__trip_update__stop_time_update__schedule_relationship__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship",
  "ScheduleRelationship",
  "TransitRealtime__TripUpdate__StopTimeUpdate__ScheduleRelationship",
  "transit_realtime",
  3,
  transit_realtime__trip_update__stop_time_update__schedule_relationship__enum_values_by_number,
  3,
  transit_realtime__trip_update__stop_time_update__schedule_relationship__enum_values_by_name,
  1,
  transit_realtime__trip_update__stop_time_update__schedule_relationship__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const TransitRealtime__TripUpdate__StopTimeUpdate__ScheduleRelationship transit_realtime__trip_update__stop_time_update__schedule_relationship__default_value = TRANSIT_REALTIME__TRIP_UPDATE__STOP_TIME_UPDATE__SCHEDULE_RELATIONSHIP__SCHEDULED;
static const ProtobufCFieldDescriptor transit_realtime__trip_update__stop_time_update__field_descriptors[5] =
{
  {
    "stop_sequence",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, has_stop_sequence),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, stop_sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arrival",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, arrival),
    &transit_realtime__trip_update__stop_time_event__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "departure",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, departure),
    &transit_realtime__trip_update__stop_time_event__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, stop_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedule_relationship",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, has_schedule_relationship),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate__StopTimeUpdate, schedule_relationship),
    &transit_realtime__trip_update__stop_time_update__schedule_relationship__descriptor,
    &transit_realtime__trip_update__stop_time_update__schedule_relationship__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__trip_update__stop_time_update__field_indices_by_name[] = {
  1,   /* field[1] = arrival */
  2,   /* field[2] = departure */
  4,   /* field[4] = schedule_relationship */
  3,   /* field[3] = stop_id */
  0,   /* field[0] = stop_sequence */
};
static const ProtobufCIntRange transit_realtime__trip_update__stop_time_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor transit_realtime__trip_update__stop_time_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TripUpdate.StopTimeUpdate",
  "StopTimeUpdate",
  "TransitRealtime__TripUpdate__StopTimeUpdate",
  "transit_realtime",
  sizeof(TransitRealtime__TripUpdate__StopTimeUpdate),
  5,
  transit_realtime__trip_update__stop_time_update__field_descriptors,
  transit_realtime__trip_update__stop_time_update__field_indices_by_name,
  1,  transit_realtime__trip_update__stop_time_update__number_ranges,
  (ProtobufCMessageInit) transit_realtime__trip_update__stop_time_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__trip_update__field_descriptors[4] =
{
  {
    "trip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, trip),
    &transit_realtime__trip_descriptor__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_time_update",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, n_stop_time_update),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, stop_time_update),
    &transit_realtime__trip_update__stop_time_update__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, vehicle),
    &transit_realtime__vehicle_descriptor__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, has_timestamp),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripUpdate, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__trip_update__field_indices_by_name[] = {
  1,   /* field[1] = stop_time_update */
  3,   /* field[3] = timestamp */
  0,   /* field[0] = trip */
  2,   /* field[2] = vehicle */
};
static const ProtobufCIntRange transit_realtime__trip_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor transit_realtime__trip_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TripUpdate",
  "TripUpdate",
  "TransitRealtime__TripUpdate",
  "transit_realtime",
  sizeof(TransitRealtime__TripUpdate),
  4,
  transit_realtime__trip_update__field_descriptors,
  transit_realtime__trip_update__field_indices_by_name,
  1,  transit_realtime__trip_update__number_ranges,
  (ProtobufCMessageInit) transit_realtime__trip_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue transit_realtime__vehicle_position__vehicle_stop_status__enum_values_by_number[3] =
{
  { "INCOMING_AT", "TRANSIT_REALTIME__VEHICLE_POSITION__VEHICLE_STOP_STATUS__INCOMING_AT", 0 },
  { "STOPPED_AT", "TRANSIT_REALTIME__VEHICLE_POSITION__VEHICLE_STOP_STATUS__STOPPED_AT", 1 },
  { "IN_TRANSIT_TO", "TRANSIT_REALTIME__VEHICLE_POSITION__VEHICLE_STOP_STATUS__IN_TRANSIT_TO", 2 },
};
static const ProtobufCIntRange transit_realtime__vehicle_position__vehicle_stop_status__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex transit_realtime__vehicle_position__vehicle_stop_status__enum_values_by_name[3] =
{
  { "INCOMING_AT", 0 },
  { "IN_TRANSIT_TO", 2 },
  { "STOPPED_AT", 1 },
};
const ProtobufCEnumDescriptor transit_realtime__vehicle_position__vehicle_stop_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.VehiclePosition.VehicleStopStatus",
  "VehicleStopStatus",
  "TransitRealtime__VehiclePosition__VehicleStopStatus",
  "transit_realtime",
  3,
  transit_realtime__vehicle_position__vehicle_stop_status__enum_values_by_number,
  3,
  transit_realtime__vehicle_position__vehicle_stop_status__enum_values_by_name,
  1,
  transit_realtime__vehicle_position__vehicle_stop_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue transit_realtime__vehicle_position__congestion_level__enum_values_by_number[5] =
{
  { "UNKNOWN_CONGESTION_LEVEL", "TRANSIT_REALTIME__VEHICLE_POSITION__CONGESTION_LEVEL__UNKNOWN_CONGESTION_LEVEL", 0 },
  { "RUNNING_SMOOTHLY", "TRANSIT_REALTIME__VEHICLE_POSITION__CONGESTION_LEVEL__RUNNING_SMOOTHLY", 1 },
  { "STOP_AND_GO", "TRANSIT_REALTIME__VEHICLE_POSITION__CONGESTION_LEVEL__STOP_AND_GO", 2 },
  { "CONGESTION", "TRANSIT_REALTIME__VEHICLE_POSITION__CONGESTION_LEVEL__CONGESTION", 3 },
  { "SEVERE_CONGESTION", "TRANSIT_REALTIME__VEHICLE_POSITION__CONGESTION_LEVEL__SEVERE_CONGESTION", 4 },
};
static const ProtobufCIntRange transit_realtime__vehicle_position__congestion_level__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex transit_realtime__vehicle_position__congestion_level__enum_values_by_name[5] =
{
  { "CONGESTION", 3 },
  { "RUNNING_SMOOTHLY", 1 },
  { "SEVERE_CONGESTION", 4 },
  { "STOP_AND_GO", 2 },
  { "UNKNOWN_CONGESTION_LEVEL", 0 },
};
const ProtobufCEnumDescriptor transit_realtime__vehicle_position__congestion_level__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.VehiclePosition.CongestionLevel",
  "CongestionLevel",
  "TransitRealtime__VehiclePosition__CongestionLevel",
  "transit_realtime",
  5,
  transit_realtime__vehicle_position__congestion_level__enum_values_by_number,
  5,
  transit_realtime__vehicle_position__congestion_level__enum_values_by_name,
  1,
  transit_realtime__vehicle_position__congestion_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const TransitRealtime__VehiclePosition__VehicleStopStatus transit_realtime__vehicle_position__current_status__default_value = TRANSIT_REALTIME__VEHICLE_POSITION__VEHICLE_STOP_STATUS__IN_TRANSIT_TO;
static const ProtobufCFieldDescriptor transit_realtime__vehicle_position__field_descriptors[8] =
{
  {
    "trip",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, trip),
    &transit_realtime__trip_descriptor__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, position),
    &transit_realtime__position__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_stop_sequence",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, has_current_stop_sequence),
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, current_stop_sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_status",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, has_current_status),
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, current_status),
    &transit_realtime__vehicle_position__vehicle_stop_status__descriptor,
    &transit_realtime__vehicle_position__current_status__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, has_timestamp),
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "congestion_level",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, has_congestion_level),
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, congestion_level),
    &transit_realtime__vehicle_position__congestion_level__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, stop_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehiclePosition, vehicle),
    &transit_realtime__vehicle_descriptor__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__vehicle_position__field_indices_by_name[] = {
  5,   /* field[5] = congestion_level */
  3,   /* field[3] = current_status */
  2,   /* field[2] = current_stop_sequence */
  1,   /* field[1] = position */
  6,   /* field[6] = stop_id */
  4,   /* field[4] = timestamp */
  0,   /* field[0] = trip */
  7,   /* field[7] = vehicle */
};
static const ProtobufCIntRange transit_realtime__vehicle_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor transit_realtime__vehicle_position__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.VehiclePosition",
  "VehiclePosition",
  "TransitRealtime__VehiclePosition",
  "transit_realtime",
  sizeof(TransitRealtime__VehiclePosition),
  8,
  transit_realtime__vehicle_position__field_descriptors,
  transit_realtime__vehicle_position__field_indices_by_name,
  1,  transit_realtime__vehicle_position__number_ranges,
  (ProtobufCMessageInit) transit_realtime__vehicle_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue transit_realtime__alert__cause__enum_values_by_number[12] =
{
  { "UNKNOWN_CAUSE", "TRANSIT_REALTIME__ALERT__CAUSE__UNKNOWN_CAUSE", 1 },
  { "OTHER_CAUSE", "TRANSIT_REALTIME__ALERT__CAUSE__OTHER_CAUSE", 2 },
  { "TECHNICAL_PROBLEM", "TRANSIT_REALTIME__ALERT__CAUSE__TECHNICAL_PROBLEM", 3 },
  { "STRIKE", "TRANSIT_REALTIME__ALERT__CAUSE__STRIKE", 4 },
  { "DEMONSTRATION", "TRANSIT_REALTIME__ALERT__CAUSE__DEMONSTRATION", 5 },
  { "ACCIDENT", "TRANSIT_REALTIME__ALERT__CAUSE__ACCIDENT", 6 },
  { "HOLIDAY", "TRANSIT_REALTIME__ALERT__CAUSE__HOLIDAY", 7 },
  { "WEATHER", "TRANSIT_REALTIME__ALERT__CAUSE__WEATHER", 8 },
  { "MAINTENANCE", "TRANSIT_REALTIME__ALERT__CAUSE__MAINTENANCE", 9 },
  { "CONSTRUCTION", "TRANSIT_REALTIME__ALERT__CAUSE__CONSTRUCTION", 10 },
  { "POLICE_ACTIVITY", "TRANSIT_REALTIME__ALERT__CAUSE__POLICE_ACTIVITY", 11 },
  { "MEDICAL_EMERGENCY", "TRANSIT_REALTIME__ALERT__CAUSE__MEDICAL_EMERGENCY", 12 },
};
static const ProtobufCIntRange transit_realtime__alert__cause__value_ranges[] = {
{1, 0},{0, 12}
};
const ProtobufCEnumValueIndex transit_realtime__alert__cause__enum_values_by_name[12] =
{
  { "ACCIDENT", 5 },
  { "CONSTRUCTION", 9 },
  { "DEMONSTRATION", 4 },
  { "HOLIDAY", 6 },
  { "MAINTENANCE", 8 },
  { "MEDICAL_EMERGENCY", 11 },
  { "OTHER_CAUSE", 1 },
  { "POLICE_ACTIVITY", 10 },
  { "STRIKE", 3 },
  { "TECHNICAL_PROBLEM", 2 },
  { "UNKNOWN_CAUSE", 0 },
  { "WEATHER", 7 },
};
const ProtobufCEnumDescriptor transit_realtime__alert__cause__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.Alert.Cause",
  "Cause",
  "TransitRealtime__Alert__Cause",
  "transit_realtime",
  12,
  transit_realtime__alert__cause__enum_values_by_number,
  12,
  transit_realtime__alert__cause__enum_values_by_name,
  1,
  transit_realtime__alert__cause__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue transit_realtime__alert__effect__enum_values_by_number[9] =
{
  { "NO_SERVICE", "TRANSIT_REALTIME__ALERT__EFFECT__NO_SERVICE", 1 },
  { "REDUCED_SERVICE", "TRANSIT_REALTIME__ALERT__EFFECT__REDUCED_SERVICE", 2 },
  { "SIGNIFICANT_DELAYS", "TRANSIT_REALTIME__ALERT__EFFECT__SIGNIFICANT_DELAYS", 3 },
  { "DETOUR", "TRANSIT_REALTIME__ALERT__EFFECT__DETOUR", 4 },
  { "ADDITIONAL_SERVICE", "TRANSIT_REALTIME__ALERT__EFFECT__ADDITIONAL_SERVICE", 5 },
  { "MODIFIED_SERVICE", "TRANSIT_REALTIME__ALERT__EFFECT__MODIFIED_SERVICE", 6 },
  { "OTHER_EFFECT", "TRANSIT_REALTIME__ALERT__EFFECT__OTHER_EFFECT", 7 },
  { "UNKNOWN_EFFECT", "TRANSIT_REALTIME__ALERT__EFFECT__UNKNOWN_EFFECT", 8 },
  { "STOP_MOVED", "TRANSIT_REALTIME__ALERT__EFFECT__STOP_MOVED", 9 },
};
static const ProtobufCIntRange transit_realtime__alert__effect__value_ranges[] = {
{1, 0},{0, 9}
};
const ProtobufCEnumValueIndex transit_realtime__alert__effect__enum_values_by_name[9] =
{
  { "ADDITIONAL_SERVICE", 4 },
  { "DETOUR", 3 },
  { "MODIFIED_SERVICE", 5 },
  { "NO_SERVICE", 0 },
  { "OTHER_EFFECT", 6 },
  { "REDUCED_SERVICE", 1 },
  { "SIGNIFICANT_DELAYS", 2 },
  { "STOP_MOVED", 8 },
  { "UNKNOWN_EFFECT", 7 },
};
const ProtobufCEnumDescriptor transit_realtime__alert__effect__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.Alert.Effect",
  "Effect",
  "TransitRealtime__Alert__Effect",
  "transit_realtime",
  9,
  transit_realtime__alert__effect__enum_values_by_number,
  9,
  transit_realtime__alert__effect__enum_values_by_name,
  1,
  transit_realtime__alert__effect__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const TransitRealtime__Alert__Cause transit_realtime__alert__cause__default_value = TRANSIT_REALTIME__ALERT__CAUSE__UNKNOWN_CAUSE;
static const TransitRealtime__Alert__Effect transit_realtime__alert__effect__default_value = TRANSIT_REALTIME__ALERT__EFFECT__UNKNOWN_EFFECT;
static const ProtobufCFieldDescriptor transit_realtime__alert__field_descriptors[7] =
{
  {
    "active_period",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, n_active_period),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, active_period),
    &transit_realtime__time_range__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "informed_entity",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, n_informed_entity),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, informed_entity),
    &transit_realtime__entity_selector__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cause",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, has_cause),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, cause),
    &transit_realtime__alert__cause__descriptor,
    &transit_realtime__alert__cause__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "effect",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, has_effect),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, effect),
    &transit_realtime__alert__effect__descriptor,
    &transit_realtime__alert__effect__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, url),
    &transit_realtime__translated_string__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_text",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, header_text),
    &transit_realtime__translated_string__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description_text",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__Alert, description_text),
    &transit_realtime__translated_string__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__alert__field_indices_by_name[] = {
  0,   /* field[0] = active_period */
  2,   /* field[2] = cause */
  6,   /* field[6] = description_text */
  3,   /* field[3] = effect */
  5,   /* field[5] = header_text */
  1,   /* field[1] = informed_entity */
  4,   /* field[4] = url */
};
static const ProtobufCIntRange transit_realtime__alert__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 10, 5 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor transit_realtime__alert__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.Alert",
  "Alert",
  "TransitRealtime__Alert",
  "transit_realtime",
  sizeof(TransitRealtime__Alert),
  7,
  transit_realtime__alert__field_descriptors,
  transit_realtime__alert__field_indices_by_name,
  3,  transit_realtime__alert__number_ranges,
  (ProtobufCMessageInit) transit_realtime__alert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__time_range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TimeRange, has_start),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TimeRange, start),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TimeRange, has_end),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TimeRange, end),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__time_range__field_indices_by_name[] = {
  1,   /* field[1] = end */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange transit_realtime__time_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor transit_realtime__time_range__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TimeRange",
  "TimeRange",
  "TransitRealtime__TimeRange",
  "transit_realtime",
  sizeof(TransitRealtime__TimeRange),
  2,
  transit_realtime__time_range__field_descriptors,
  transit_realtime__time_range__field_indices_by_name,
  1,  transit_realtime__time_range__number_ranges,
  (ProtobufCMessageInit) transit_realtime__time_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__position__field_descriptors[5] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, latitude),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, longitude),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bearing",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, has_bearing),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, bearing),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "odometer",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, has_odometer),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, odometer),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, has_speed),
    PROTOBUF_C_OFFSETOF(TransitRealtime__Position, speed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__position__field_indices_by_name[] = {
  2,   /* field[2] = bearing */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = odometer */
  4,   /* field[4] = speed */
};
static const ProtobufCIntRange transit_realtime__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor transit_realtime__position__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.Position",
  "Position",
  "TransitRealtime__Position",
  "transit_realtime",
  sizeof(TransitRealtime__Position),
  5,
  transit_realtime__position__field_descriptors,
  transit_realtime__position__field_indices_by_name,
  1,  transit_realtime__position__number_ranges,
  (ProtobufCMessageInit) transit_realtime__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue transit_realtime__trip_descriptor__schedule_relationship__enum_values_by_number[5] =
{
  { "SCHEDULED", "TRANSIT_REALTIME__TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__SCHEDULED", 0 },
  { "ADDED", "TRANSIT_REALTIME__TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__ADDED", 1 },
  { "UNSCHEDULED", "TRANSIT_REALTIME__TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__UNSCHEDULED", 2 },
  { "CANCELED", "TRANSIT_REALTIME__TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__CANCELED", 3 },
  { "REPLACEMENT", "TRANSIT_REALTIME__TRIP_DESCRIPTOR__SCHEDULE_RELATIONSHIP__REPLACEMENT", 5 },
};
static const ProtobufCIntRange transit_realtime__trip_descriptor__schedule_relationship__value_ranges[] = {
{0, 0},{5, 4},{0, 5}
};
const ProtobufCEnumValueIndex transit_realtime__trip_descriptor__schedule_relationship__enum_values_by_name[5] =
{
  { "ADDED", 1 },
  { "CANCELED", 3 },
  { "REPLACEMENT", 4 },
  { "SCHEDULED", 0 },
  { "UNSCHEDULED", 2 },
};
const ProtobufCEnumDescriptor transit_realtime__trip_descriptor__schedule_relationship__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "transit_realtime.TripDescriptor.ScheduleRelationship",
  "ScheduleRelationship",
  "TransitRealtime__TripDescriptor__ScheduleRelationship",
  "transit_realtime",
  5,
  transit_realtime__trip_descriptor__schedule_relationship__enum_values_by_number,
  5,
  transit_realtime__trip_descriptor__schedule_relationship__enum_values_by_name,
  2,
  transit_realtime__trip_descriptor__schedule_relationship__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor transit_realtime__trip_descriptor__field_descriptors[5] =
{
  {
    "trip_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, trip_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, start_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_date",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, start_date),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedule_relationship",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, has_schedule_relationship),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, schedule_relationship),
    &transit_realtime__trip_descriptor__schedule_relationship__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TripDescriptor, route_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__trip_descriptor__field_indices_by_name[] = {
  4,   /* field[4] = route_id */
  3,   /* field[3] = schedule_relationship */
  2,   /* field[2] = start_date */
  1,   /* field[1] = start_time */
  0,   /* field[0] = trip_id */
};
static const ProtobufCIntRange transit_realtime__trip_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor transit_realtime__trip_descriptor__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TripDescriptor",
  "TripDescriptor",
  "TransitRealtime__TripDescriptor",
  "transit_realtime",
  sizeof(TransitRealtime__TripDescriptor),
  5,
  transit_realtime__trip_descriptor__field_descriptors,
  transit_realtime__trip_descriptor__field_indices_by_name,
  1,  transit_realtime__trip_descriptor__number_ranges,
  (ProtobufCMessageInit) transit_realtime__trip_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__vehicle_descriptor__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehicleDescriptor, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehicleDescriptor, label),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "license_plate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__VehicleDescriptor, license_plate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__vehicle_descriptor__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = label */
  2,   /* field[2] = license_plate */
};
static const ProtobufCIntRange transit_realtime__vehicle_descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor transit_realtime__vehicle_descriptor__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.VehicleDescriptor",
  "VehicleDescriptor",
  "TransitRealtime__VehicleDescriptor",
  "transit_realtime",
  sizeof(TransitRealtime__VehicleDescriptor),
  3,
  transit_realtime__vehicle_descriptor__field_descriptors,
  transit_realtime__vehicle_descriptor__field_indices_by_name,
  1,  transit_realtime__vehicle_descriptor__number_ranges,
  (ProtobufCMessageInit) transit_realtime__vehicle_descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__entity_selector__field_descriptors[5] =
{
  {
    "agency_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, agency_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, route_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, has_route_type),
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, route_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trip",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, trip),
    &transit_realtime__trip_descriptor__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__EntitySelector, stop_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__entity_selector__field_indices_by_name[] = {
  0,   /* field[0] = agency_id */
  1,   /* field[1] = route_id */
  2,   /* field[2] = route_type */
  4,   /* field[4] = stop_id */
  3,   /* field[3] = trip */
};
static const ProtobufCIntRange transit_realtime__entity_selector__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor transit_realtime__entity_selector__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.EntitySelector",
  "EntitySelector",
  "TransitRealtime__EntitySelector",
  "transit_realtime",
  sizeof(TransitRealtime__EntitySelector),
  5,
  transit_realtime__entity_selector__field_descriptors,
  transit_realtime__entity_selector__field_indices_by_name,
  1,  transit_realtime__entity_selector__number_ranges,
  (ProtobufCMessageInit) transit_realtime__entity_selector__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__translated_string__translation__field_descriptors[2] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TranslatedString__Translation, text),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TransitRealtime__TranslatedString__Translation, language),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__translated_string__translation__field_indices_by_name[] = {
  1,   /* field[1] = language */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange transit_realtime__translated_string__translation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor transit_realtime__translated_string__translation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TranslatedString.Translation",
  "Translation",
  "TransitRealtime__TranslatedString__Translation",
  "transit_realtime",
  sizeof(TransitRealtime__TranslatedString__Translation),
  2,
  transit_realtime__translated_string__translation__field_descriptors,
  transit_realtime__translated_string__translation__field_indices_by_name,
  1,  transit_realtime__translated_string__translation__number_ranges,
  (ProtobufCMessageInit) transit_realtime__translated_string__translation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transit_realtime__translated_string__field_descriptors[1] =
{
  {
    "translation",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TransitRealtime__TranslatedString, n_translation),
    PROTOBUF_C_OFFSETOF(TransitRealtime__TranslatedString, translation),
    &transit_realtime__translated_string__translation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transit_realtime__translated_string__field_indices_by_name[] = {
  0,   /* field[0] = translation */
};
static const ProtobufCIntRange transit_realtime__translated_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor transit_realtime__translated_string__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "transit_realtime.TranslatedString",
  "TranslatedString",
  "TransitRealtime__TranslatedString",
  "transit_realtime",
  sizeof(TransitRealtime__TranslatedString),
  1,
  transit_realtime__translated_string__field_descriptors,
  transit_realtime__translated_string__field_indices_by_name,
  1,  transit_realtime__translated_string__number_ranges,
  (ProtobufCMessageInit) transit_realtime__translated_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
