CC=gcc

all:
	$(CC) -c -Wextra -Wall -ansi -pedantic commercial_modes.c
	$(CC) -c -Wextra -Wall -ansi -pedantic journey_pattern_points.c
	$(CC) -c -Wextra -Wall -ansi -pedantic journey_patterns.c
	$(CC) -c -Wextra -Wall -ansi -pedantic journey_patterns_indexed.c
	$(CC) -c -Wextra -Wall -ansi -pedantic lines.c
	$(CC) -c -Wextra -Wall -ansi -pedantic operators.c
	$(CC) -c -Wextra -Wall -ansi -pedantic physical_modes.c
	$(CC) -c -Wextra -Wall -ansi -pedantic routes.c
	$(CC) -c -Wextra -Wall -ansi -pedantic stop_areas.c
	$(CC) -c -Wextra -Wall -ansi -pedantic stop_points.c
	$(CC) -c -Wextra -Wall -ansi -pedantic stop_times.c
	$(CC) -c -Wextra -Wall -ansi -pedantic string_pool.c
	$(CC) -c -Wextra -Wall -ansi -pedantic transfers.c
	$(CC) -c -Wextra -Wall -ansi -pedantic vehicle_journeys.c
	$(CC) -c -Wextra -Wall -ansi -pedantic vehicle_transfers.c
	$(CC) -c -Wextra -Wall -ansi -pedantic container.c

clean:
	rm *.o
