CC=gcc

all:
	$(CC) -O0 -ggdb3 -Wextra -Wall -ansi -pedantic -I.. -o test_stop_areas ../stop_areas.c ../string_pool.c test_stop_areas.c
	$(CC) -O0 -ggdb3 -Wextra -Wall -ansi -pedantic -I.. -o test_stop_points ../stop_points.c ../string_pool.c test_stop_points.c
	$(CC) -O0 -ggdb3 -Wextra -Wall -ansi -pedantic -I.. -o test_operators ../operators.c ../string_pool.c test_operators.c

